# Generated by Django 3.2 on 2024-08-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="customuser",
            name="confirmation_code",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.SlugField(
                choices=[
                    ("user", "user"),
                    ("admin", "admin"),
                    ("moderator", "moderator"),
                ],
                default="user",
            ),
        ),
    ]
